language: node_js
node_js:
- v9.6.1
cache:
  directories:
  - node_modules
script:
- npm test
- npm run build
deploy:
  skip_cleanup: true
  keyfile: client-secret.json
  provider: gae
  project: vesselbuilder-frontend
  default: true
  docker-build: remote
  on:
    branches:    # ← new!
      only:      # ← new!
        - master # ← new!
true:
  branch: master
services:
- docker

before-install:
- openssl aes-256-cbc -K $encrypted_c1f00c53dfe2_key -iv $encrypted_c1f00c53dfe2_iv -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar xvzf credentials.tar.gz

email: false
